version: "2"
services:
  app:
    container_name: rentomojo
    restart: always
    build: ./
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"